---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins # Use the jenkins namespace
spec:
  accessModes:
    - ReadWriteOnce # Allow this to be mounted ONLY by a single node
  resources:
    requests:
      storage: 5Gi # Request for 5Gi of persistent disk storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins      
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
          ports:
            - containerPort: 8080
 
          volumeMounts:
          - name: jenkins-data # It could be any name
            mountPath: /var/jenkins_home # Jenkins home path inside the pod
      volumes:
        - name: jenkins-data # Volume name defined above
          persistentVolumeClaim:
            claimName: jenkins               
---

apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: master    # Set a the port's name
    - port: 50000     # Enable port for executors
      name: executors
  type: LoadBalancer
